server:
  port: 8888
spring:
  application:
    name: JPA_API_DEMO
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        # show_sql: true
        default_batch_fetch_size: 500
  datasource:
    url: jdbc:postgresql://localhost:5501/XPRODB
    username: XADMIN
    password: XADMIN
    driver-class-name: org.postgresql.Driver


